[package]
name = "snarkvm-circuits-environment"
version = "0.7.5"
authors = [ "The Aleo Team <hello@aleo.org>" ]
description = "Circuit environment for a decentralized virtual machine"
license = "GPL-3.0"
edition = "2021"

[[bench]]
name = "linear_combination"
path = "benches/linear_combination.rs"
harness = false

[dependencies.snarkvm-circuits-environment-witness]
path = "./witness"
version = "0.7.5"
default-features = false

[dependencies.snarkvm-curves]
path = "../../curves"
version = "0.7.5"
default-features = false

[dependencies.snarkvm-fields]
path = "../../fields"
version = "0.7.5"
default-features = false

[dependencies.snarkvm-r1cs]
path = "../../r1cs"
version = "0.7.5"
default-features = false

[dependencies.snarkvm-utilities]
path = "../../utilities"
version = "0.7.5"
default-features = false

[dependencies.indexmap]
version = "1.8.1"

[dependencies.itertools]
version = "0.10.1"

[dependencies.nom]
version = "7.1"

[dependencies.num-derive]
version = "0.3"

[dependencies.num-traits]
version = "0.2"

[dependencies.once_cell]
version = "1.10.0"

[dependencies.rayon]
version = "1"

[dev-dependencies.snarkvm-algorithms]
path = "../../algorithms"
version = "0.7.5"
default-features = false
features = ["polycommit", "snark"]

[dev-dependencies.snarkvm-circuits]
path = "../../circuits"
version = "0.7.5"

[dev-dependencies.criterion]
version = "0.3"

[features]
default = ["snarkvm-curves/default", "snarkvm-r1cs/default"]
